#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#+    Listens on port 80.
#+    Returns a page containing "Hello World!" when queried
#++    at the root with a curl GET request.

sudo apt update
sudo apt install nginx
sudo chown -R $USER:$USER /var/www
echo "Hello World!" > /var/www/html/index.nginx-debian.html
printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.htm;
}
sudo service nginx start


